spring.application.name=biblioteca-api

spring.datasource.url=jdbc:postgresql://dpg-d7hci9navr4c73f0dsu0-a.virginia-postgres.render.com:5432/ghostbot_0kij
spring.datasource.username=ghostbot_0kij_user
spring.datasource.password=wmTjDC9TXjlcM8S0tl7fr755zF4kg2Pi

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970